version: 2
updates:
  - package-ecosystem: npm
    directory: /a
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /b
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /c
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /d
    schedule:
      interval: daily
